networks:
  itu-minitwit-network:
    external: false

services:
  minitwitserver:
    platform: "linux/amd64"
    image: bennyboomblaster/minitwitimage:latest
    container_name: chirp
    ports:
      - "7273:7273"
    environment:
      - "ConnectionStrings__DefaultConnection=Host=db-postgresql-fra1-72367-do-user-33600044-0.e.db.ondigitalocean.com;Port=25060;Database=chirp;Username=doadmin;Password=${POSTGRES_PSW};SSL Mode=Require"
    volumes:
      - ./latest.txt:/app/data/latest.txt
    networks:
      - itu-minitwit-network
    depends_on:
      - grafana
      - prometheus
      - loki

  alloy:
    image: grafana/alloy@sha256:e3a1fff5eee8e2535fb75b350d0ccb722149720c788e57fd8d93b33e9163d85b
    container_name: alloy
    volumes:
      - ./alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:  run --server.http.listen-addr=0.0.0.0:4000 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - "4000:4000"
    networks:
      - itu-minitwit-network
    restart: unless-stopped

  loki:
    image: grafana/loki@sha256:535a14ffef1d48099fc7f940da51bbcb253fcc63c6918e070f60caa53c82bf5c
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/loki
    command: -config.file=/etc/loki/loki-config.yml
    networks:
      - itu-minitwit-network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus@sha256:4a61322ac1103a0e3aea2a61ef1718422a48fa046441f299d71e660a3bc71ae9
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - itu-minitwit-network

  grafana:
    image: grafana/grafana@sha256:7227fe2aca02ad399c8de438ceaae7687415da2abc763665795858edbe48819c
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasource/datasource.yml
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=helgeandfriends
      - GF_SECURITY_ADMIN_PASSWORD=sesame0uvr3toi
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - itu-minitwit-network  
volumes:
  loki-data:
  grafana-storage: {}
