name: ShellCheck

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'report/**'
jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'       
          severity: warning          # fail only on warning or above
        env:
          SHELLCHECK_OPTS: -e SC2034 # suppress specific rules