name: Trivy Docker Scan

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'report/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'report/**'

jobs:
  container-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.6
        with:
          version: v0.69.3

      - name: Build Docker image
        run: docker build -t chirp .

      - name: Run Trivy scan
        run: trivy image chirp --exit-code 1 --severity HIGH,CRITICAL